### ISSUE TITLE
Support Full Head Swap ?

### ISSUE THREAD

**Issue by quicksandznzn** [ygtxr1997/ReliableSwap#2]

**Comment by ygtxr1997** [comment]
We only focus on Face Swapping.
For Head Swapping, [HeSer](https://github.com/jmliu88/HeSer) seems to be a good method, but they haven't released their codes yet.

**Comment by quicksandznzn** [comment]
> We only focus on Face Swapping. For Head Swapping, [HeSer](https://github.com/jmliu88/HeSer) seems to be a good method, but they haven't released their codes yet.

Yep,Thanks
